---
title: "Martin Ranch flux tower data"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F)
```

### Location: 30.8167, -99.8619
### Texas A&M University

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(ggpubr) 
library(data.table)
library(lubridate)
library(plyr)

## For reading TOA5 file
source('~/Documents/R/SVNA/Flux data/importCSdata.R')

# Import data
weather_data_S <- importCSdata('martin_flux.dat')
#setDT(weather_data_S)
weather_data_S$TIMESTAMP <- as.POSIXct(weather_data_S$TIMESTAMP) ## ddply() doesn't like POSIXTlt
weather_data_S$Date <- date(weather_data_S$TIMESTAMP)
```

### Summary plots:
Half-hourly data from `r weather_data_S$TIMESTAMP[1]` to `r weather_data_S$TIMESTAMP[nrow(weather_data_S)]`

```{r, echo=FALSE}
ggplot(weather_data_S, aes(x = TIMESTAMP, y = AirTC_Avg)) + 
  xlab("Date - Martin (flux tower)") +
  ylab("Air temperature (C)") +
  geom_line() +
#  geom_point(size = 3) +
  theme_pubr()

Precip_daily_S <- ddply(weather_data_S, c("Date"), summarise,
                   N    = length(Rain_mm_Tot),
                   sum = sum(Rain_mm_Tot)
)

ggplot(Precip_daily_S, aes(x = Date, y = sum)) + 
  xlab("Date - Martin (flux tower)") +
  ylab("Daily Precipitation (mm)") +
  geom_col() +
  theme_pubr()


ggplot(weather_data_S, aes(x = TIMESTAMP, y = VWC_Avg)) + 
  xlab("Date - Martin (flux tower)") +
  ylab("Soil volumetric water content (@ 5 cm)") +
  geom_line() +
  #  geom_point(size = 3) +
  theme_pubr()

ggplot(weather_data_S, aes(x = TIMESTAMP, y = ST_Avg)) + 
  xlab("Date - Martin (flux tower)") +
  ylab("Soil temperature (C; @ 5 cm)") +
  geom_line() +
  #  geom_point(size = 3) +
  theme_pubr()

ggplot(weather_data_S, aes(x = TIMESTAMP, y = RH)) + 
  xlab("Date - Martin (flux tower)") +
  ylab("Relative Humidity (%)") +
  geom_line() +
  #  geom_point(size = 3) +
  theme_pubr()  
```

